// Проверява всички линкове в data.json — кои работят, кои са счупени/паркирани.
// Стартиране: node scripts/audit-links.mjs <път-до-data.json>
import { readFileSync } from 'node:fs'

const file = process.argv[2]
if (!file) { console.error('Липсва път до data.json'); process.exit(1) }
const items = JSON.parse(readFileSync(file, 'utf-8'))

const PARK_HOSTS = ['godaddy', 'sedo', 'dan.com', 'afternic', 'sav.com', 'hugedomains',
  'bodis', 'parkingcrew', 'above.com', 'uniregistry', 'domainmarket', 'namecheap.com/domains']
const PARK_WORDS = ['domain is for sale', 'buy this domain', 'this domain may be for sale',
  'the domain', 'is for sale', 'домейнът', 'купете този домейн', 'parked domain',
  'domain for sale', 'this webpage was generated by the domain owner', 'godaddy']

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'

async function check(url) {
  const ctrl = new AbortController()
  const t = setTimeout(() => ctrl.abort(), 8000)
  try {
    const res = await fetch(url, { redirect: 'follow', signal: ctrl.signal, headers: { 'User-Agent': UA, Accept: 'text/html' } })
    const finalHost = new URL(res.url).hostname.toLowerCase()
    let bodyStart = ''
    try { bodyStart = (await res.text()).slice(0, 4000).toLowerCase() } catch {}
    const parkedHost = PARK_HOSTS.some((h) => finalHost.includes(h))
    const parkedBody = PARK_WORDS.some((w) => bodyStart.includes(w)) && bodyStart.length < 3500
    if (parkedHost) return { verdict: 'PARKED', info: `→ ${finalHost}` }
    if (res.status === 404 || res.status === 410) return { verdict: 'DEAD', info: `${res.status}` }
    if (res.status === 403 || res.status === 429) return { verdict: 'BLOCKED', info: `${res.status} (най-вероятно ОК за хора)` }
    if (parkedBody) return { verdict: 'PARKED?', info: `подозрителен кратък текст` }
    if (res.ok) return { verdict: 'OK', info: `${res.status}` }
    return { verdict: 'CHECK', info: `${res.status}` }
  } catch (e) {
    const msg = String(e.message || e)
    if (msg.includes('ENOTFOUND') || msg.includes('getaddrinfo')) return { verdict: 'DEAD', info: 'домейнът не съществува' }
    if (msg.includes('aborted') || msg.includes('timeout')) return { verdict: 'TIMEOUT', info: 'няма отговор' }
    return { verdict: 'ERR', info: msg.slice(0, 60) }
  } finally {
    clearTimeout(t)
  }
}

for (const b of items) {
  const links = b.links || []
  if (!links.length) continue
  const results = await Promise.all(links.map(async (l) => ({ l, r: await check(l.url) })))
  const bad = results.filter((x) => ['PARKED', 'PARKED?', 'DEAD', 'TIMEOUT'].includes(x.r.verdict))
  if (bad.length || results.some((x) => x.r.verdict !== 'OK' && x.r.verdict !== 'BLOCKED')) {
    console.log(`\n### ${b.name}`)
    for (const { l, r } of results) {
      console.log(`  [${r.verdict}] ${l.label}: ${l.url}  ${r.info}`)
    }
  }
}
console.log('\n--- край ---')
